# Generated by Django 6.0.5 on 2026-05-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gerencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo (Clasificación)',
                'verbose_name_plural': 'Motivos (Clasificación)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DescansoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, default='')),
                ('archivo_origen', models.CharField(blank=True, default='', max_length=255)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descansos', to='descansos.gerencia')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descansos', to='descansos.motivo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to='descansos.paciente')),
            ],
            options={
                'ordering': ['-fecha_inicio', 'paciente__nombre'],
                'indexes': [models.Index(fields=['fecha_inicio'], name='descansos_d_fecha_i_c92bed_idx'), models.Index(fields=['gerencia'], name='descansos_d_gerenci_1e6594_idx'), models.Index(fields=['motivo'], name='descansos_d_motivo__cb9299_idx')],
                'constraints': [models.UniqueConstraint(fields=('paciente', 'fecha_inicio', 'fecha_fin'), name='uniq_descanso_paciente_periodo')],
            },
        ),
    ]
