# Generated by Django 6.0.5 on 2026-05-20 23:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descansos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio', models.CharField(choices=[('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('otro', 'Otro')], default='llamada', max_length=20)),
                ('estado', models.CharField(choices=[('contactado', 'Contactado'), ('sin_respuesta', 'Sin respuesta'), ('numero_erroneo', 'Número erróneo'), ('no_disponible', 'No disponible'), ('otro', 'Otro')], default='contactado', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('proximo_contacto', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='descansos.paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['paciente', '-fecha'], name='descansos_s_pacient_666f2a_idx')],
            },
        ),
    ]
